name: "⚙ Esteira de Build NPM"
on:
  push:
    paths-ignore:
      - ".github/workflows/**"
    branches:
      - main
      - "feat!/**"
      - "feature!/**"
      - "fix!/**"
      - "feat/**"
      - "feature/**"
      - "fix/**"
      - "refactor/**"
      - "doc/**"
  pull_request:
    types:
      - opened
    branches:
      - main
  workflow_dispatch:
    inputs:
      publica_versao_fechada_branch_auxiliar:
        type: boolean
        description: "Publicar versão fechada fora da branch main"
        default: false
permissions:
  actions: write
  contents: write
  pull-requests: write
jobs:
  CI:
    uses: bbvinet/aic-workflow-npm/.github/workflows/workflow.yml@v1
    with:
      plataforma_aplicacao: cloud
      publica_versao_fechada_branch_auxiliar: ${{ github.event.inputs.publica_versao_fechada_branch_auxiliar }}
    secrets: inherit
  CD-des:
    needs: CI
    if: needs.CI.outputs.autodeploy == 'true'
    name: "CD (desenvolvimento)"
    uses: bbvinet/aic-workflow-autodeploy-cloud/.github/workflows/autodeploy.yml@v1
    with:
      versao: ${{ needs.CI.outputs.versao_projeto }}
      ambiente: ${{ needs.CI.outputs.canal }}/desenvolvimento
      repositorio: ${{ needs.CI.outputs.repositorio_deploy }}
      matricula: ${{ needs.CI.outputs.matricula_solicitante }}       
    secrets: inherit
