version: "3"
services:
  app:
    container_name: psc-sre-automacao-controller
    image: psc-sre-automacao-controller
    build:
      context: ../
      dockerfile: Dockerfile
    user: "${MY_UID}:${MY_GID}"
    command: npm run dev
    network_mode: host
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ../:/app
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      NODE_ENV: localhost
      APP_HOST: 0.0.0.0
      API_PORT: 3000
      ENABLE_LOG_HTTP: 1
      OSS_ACCESS_KEY_FILE: /run/secrets/oss_access_key
      OSS_SECRET_KEY_FILE: /run/secrets/oss_secret_key
    secrets:
      - oss_access_key
      - oss_secret_key
    healthcheck:
      test: curl -f --noproxy 'localhost' http://localhost:3000/health
      interval: 20s
      timeout: 5s
      retries: 5
secrets:
  oss_access_key:
    file: ./.secrets/oss_access_key
  oss_secret_key:
    file: ./.secrets/oss_secret_key

