#!/usr/bin/env bash
set -euo pipefail

# Codex autonomous git flow:
# commit -> push -> PR -> auto-merge (when allowed)

REPO="${REPO:-lucassfreiree/autopilot}"
BASE_BRANCH="${BASE_BRANCH:-main}"
MERGE_MODE="${MERGE_MODE:-squash}"
AUTO_MERGE="${AUTO_MERGE:-true}"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$BRANCH" == "$BASE_BRANCH" ]]; then
  echo "[ERROR] Current branch is '$BASE_BRANCH'. Create/use a feature branch first." >&2
  exit 1
fi

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo "[ERROR] GITHUB_TOKEN is required." >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "[ERROR] gh CLI is required." >&2
  exit 1
fi

if ! git remote get-url origin >/dev/null 2>&1; then
  git remote add origin "https://github.com/${REPO}.git"
  echo "[INFO] origin configured: https://github.com/${REPO}.git"
fi

REMOTE_URL="$(git remote get-url origin)"
echo "[INFO] remote origin: ${REMOTE_URL}"

echo "[INFO] pushing branch ${BRANCH}"
git push -u origin "$BRANCH"

# Authenticate gh for this command scope
export GH_TOKEN="$GITHUB_TOKEN"

PR_URL=""
if gh pr view "$BRANCH" --repo "$REPO" >/dev/null 2>&1; then
  echo "[INFO] PR already exists for branch ${BRANCH}"
  PR_URL="$(gh pr view "$BRANCH" --repo "$REPO" --json url --jq .url)"
else
  TITLE="${PR_TITLE:-chore: auto PR from ${BRANCH}}"
  BODY="${PR_BODY:-Auto-generated by scripts/codex/auto-pr-merge.sh}"
  PR_URL="$(gh pr create --repo "$REPO" --base "$BASE_BRANCH" --head "$BRANCH" --title "$TITLE" --body "$BODY")"
  echo "[INFO] PR created: ${PR_URL}"
fi

if [[ "$AUTO_MERGE" == "true" ]]; then
  echo "[INFO] enabling auto-merge (${MERGE_MODE})"
  gh pr merge "$BRANCH" --repo "$REPO" --auto --"$MERGE_MODE"
fi

echo "[DONE] ${PR_URL}"
