#!/usr/bin/env bash
set -euo pipefail

# Codex autonomous git flow:
# commit -> push -> PR -> auto-merge (when allowed)

REPO="${REPO:-lucassfreiree/autopilot}"
BASE_BRANCH="${BASE_BRANCH:-main}"
MERGE_MODE="${MERGE_MODE:-squash}"
AUTO_MERGE="${AUTO_MERGE:-true}"
AUTO_COMMIT="${AUTO_COMMIT:-true}"
COMMIT_MESSAGE="${COMMIT_MESSAGE:-chore: codex autonomous update}"
COMMIT_MARKER="${COMMIT_MARKER:-[claude]}"
REQUIRE_PREFLIGHT="${REQUIRE_PREFLIGHT:-true}"
PREFLIGHT_CMD="${PREFLIGHT_CMD:-scripts/codex/preflight-autopilot.sh}"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$BRANCH" == "$BASE_BRANCH" ]]; then
  echo "[ERROR] Current branch is '$BASE_BRANCH'. Create/use a feature branch first." >&2
  exit 1
fi

if [[ "$REPO" == "lucassfreiree/autopilot" ]] && [[ "$REQUIRE_PREFLIGHT" == "true" ]]; then
  if [[ -x "$PREFLIGHT_CMD" ]]; then
    echo "[INFO] running preflight validations before push/PR/merge"
    "$PREFLIGHT_CMD"
  else
    echo "[ERROR] preflight command not found or not executable: $PREFLIGHT_CMD" >&2
    exit 1
  fi
fi

if [[ "$REPO" == "lucassfreiree/autopilot" ]] && [[ "$COMMIT_MESSAGE" != *"$COMMIT_MARKER"* ]]; then
  COMMIT_MESSAGE="${COMMIT_MARKER} ${COMMIT_MESSAGE}"
fi

if [[ "$AUTO_COMMIT" == "true" ]]; then
  if [[ -n "$(git status --porcelain)" ]]; then
    echo "[INFO] local changes detected, creating commit automatically"
    git add -A
    git commit -m "$COMMIT_MESSAGE"
  else
    echo "[INFO] no local changes to commit"
  fi
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "[ERROR] gh CLI is required." >&2
  exit 1
fi

# Token resolution order:
# 1) GITHUB_TOKEN
# 2) GH_TOKEN
# 3) gh auth token (if user already authenticated)
TOKEN="${GITHUB_TOKEN:-${GH_TOKEN:-}}"
if [[ -z "${TOKEN}" ]]; then
  TOKEN="$(gh auth token 2>/dev/null || true)"
fi

if [[ -z "${TOKEN}" ]]; then
  echo "[ERROR] Missing token. Set GITHUB_TOKEN or GH_TOKEN, or run gh auth login." >&2
  exit 1
fi

if ! git remote get-url origin >/dev/null 2>&1; then
  git remote add origin "https://github.com/${REPO}.git"
  echo "[INFO] origin configured: https://github.com/${REPO}.git"
fi

REMOTE_URL="$(git remote get-url origin)"
echo "[INFO] remote origin: ${REMOTE_URL}"

echo "[INFO] pushing branch ${BRANCH}"
git push -u origin "$BRANCH"

# Authenticate gh for this command scope
export GH_TOKEN="$TOKEN"

PR_URL=""
PR_NUMBER="$(gh pr list --repo "$REPO" --head "$BRANCH" --base "$BASE_BRANCH" --state open --json number --jq '.[0].number // empty')"
if [[ -n "$PR_NUMBER" ]]; then
  echo "[INFO] PR already exists for branch ${BRANCH}: #${PR_NUMBER}"
  PR_URL="$(gh pr view "$PR_NUMBER" --repo "$REPO" --json url --jq .url)"
else
  TITLE="${PR_TITLE:-chore: auto PR from ${BRANCH}}"
  BODY="${PR_BODY:-Auto-generated by scripts/codex/auto-pr-merge.sh}"
  PR_URL="$(gh pr create --repo "$REPO" --base "$BASE_BRANCH" --head "$BRANCH" --title "$TITLE" --body "$BODY")"
  PR_NUMBER="$(gh pr view "$BRANCH" --repo "$REPO" --json number --jq .number 2>/dev/null || true)"
  echo "[INFO] PR created: ${PR_URL}"
fi

if [[ "$AUTO_MERGE" == "true" ]]; then
  TARGET="${PR_NUMBER:-$BRANCH}"
  echo "[INFO] enabling auto-merge (${MERGE_MODE}) for ${TARGET}"
  if ! gh pr merge "$TARGET" --repo "$REPO" --auto --"$MERGE_MODE"; then
    echo "[WARN] Auto-merge unavailable (likely branch protection). Falling back to direct merge."
    gh pr merge "$TARGET" --repo "$REPO" --"$MERGE_MODE" --delete-branch
  fi
fi

echo "[DONE] ${PR_URL}"
