global:
  idx: ""
  clusterName: ""
  argocdObjectsNamespace: ""
  annotationsComunsAdicionais: {}
  capRepoGitURL: ""
  targetRevision: ""
  clusterDistribuicao: ""
  pipeline: ""
  servicoEnv: ""
appset:
  enabled: true
  items:
    - apiVersion: argoproj.io/v1alpha1
      kind: ApplicationSet
      metadata:
        labels:
          release.k8s.bb/tipo: cap
          cap.k8s.bb/name: "{{.Values.global.servicoNome}}"
          cap.k8s.bb/sigla: "{{.Values.global.servicoSigla}}"
          release.k8s.bb/env: "{{.Values.global.servicoEnv}}"
          pipeline: "{{.Values.global.pipeline}}"
        name: "{{.Values.global.clusterName}}-{{.Values.global.servicoSigla}}-{{.Values.global.servicoNome}}-{{.Values.global.pipeline}}"
        namespace: "{{.Values.global.argocdObjectsNamespace}}"
      spec:
        goTemplate: true
        goTemplateOptions: ["missingkey=error"]
        ignoreApplicationDifferences:
        - jsonPointers:
          - /spec/syncPolicy
        generators:
        - clusters:
            selector:
              matchExpressions:
                - key: "{{.Values.global.servicoNome}}.config.cap.k8s.bb/enabled"
                  operator: In
                  values: ["true"]
                - key: "{{.Values.global.servicoNome}}.config.cap.k8s.bb/deploy"
                  operator: In
                  values: ["true"]
                - key: '{{.Values.global.servicoNome}}.config.cap.k8s.bb/pipeline'
                  operator: In
                  values:
                    - "{{.Values.global.pipeline}}"
                - key: cluster.k8s.bb/name
                  operator: In
                  values: 
                  - "{{.Values.global.clusterName}}"
            values: {}
        syncPolicy:
          preserveResourcesOnDeletion: true
        template:
          metadata:
            annotations:
              argocd.argoproj.io/manifest-generate-paths: .
              # argocd.argoproj.io/sync-options: Prune=false
              # link.argocd.argoproj.io/external-link: ""
            labels:
              release.k8s.bb/tipo: cap
              cap.k8s.bb/name: "{{.Values.global.servicoNome}}"
              cap.k8s.bb/sigla: "{{.Values.global.servicoSigla}}"
              release.k8s.bb/env: "{{.Values.global.servicoEnv}}"
              cluster.k8s.bb/name: '{{.Values.global.clusterName}}'
              pipeline: "{{.Values.global.pipeline}}"
            name: '{{.Values.global.clusterName}}-{{.Values.global.servicoSigla}}-{{.Values.global.servicoNome}}-{{.Values.global.pipeline}}'
          spec:
            ignoreDifferences: []
            syncPolicy:
              managedNamespaceMetadata:
                labels: # The labels to set on the application namespace
                  release.k8s.bb/sigla: psc
                annotations: # The annotations to set on the application namespace
                  release.k8s.bb/gitUrl: "{{.Values.global.capRepoGitURL}}"
                  # scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Equal", "effect": "NoSchedule", "key": "node.k8s.bb/servico", "value": "psc-groupsync-operator-infra"} , {"operator": "Equal", "effect": "NoSchedule", "key": "node.k8s.bb/servico", "value": "metrics"} , {"operator": "Exists", "effect": "NoSchedule", "key": "node.k8s.bb/site"} , {"operator": "Exists", "effect": "NoSchedule", "key": "node-role.kubernetes.io/infra"}]'
              syncOptions:
              # - ApplyOutOfSyncOnly=true
              - CreateNamespace=true
              automated:
                prune: true
                selfHeal: true
            destination:
              namespace: '{{.Values.global.servicoSigla}}-{{.Values.global.servicoNome}}'
              name: '{{.Values.global.clusterName}}'
            project: "{{.Values.global.servicoSigla}}-{{.Values.global.servicoNome}}-{{.Values.global.servicoEnv}}-{{.Values.global.pipeline}}"
            sources:
            - path: "releases/{{.Values.global.clusterDistribuicao}}/{{.Values.global.servicoEnv}}/deploy"
              repoURL: "{{.Values.global.capRepoGitURL}}"
              targetRevision: "{{.Values.global.targetRevision}}"
              helm:
                releaseName: "{{.Values.global.clusterName}}-{{.Values.global.servicoNome}}-deploy"
                valueFiles:
                  - values.yaml
                values: |
                  global:
                    servicoNamespace: {{.Values.global.servicoSigla}}-{{.Values.global.servicoNome}}
                    servicoNome: {{.Values.global.servicoNome}}
                    servicoSigla: {{.Values.global.servicoSigla}}
                    servicoNomeCompleto: {{.Values.global.servicoSigla}}-{{.Values.global.servicoNome}}
                    servicoEnv: {{.Values.global.servicoEnv}}
                    clusterName: {{.Values.global.clusterName}}
                    clusterSolucao: '{{`{{`}}index .metadata.labels "cluster.k8s.bb/solucao"{{`}}`}}'
                    clusterServico: '{{`{{`}}index .metadata.labels "solucao.cluster.k8s.bb/servico"{{`}}`}}'
                    clusterDimensao: '{{`{{`}}index .metadata.labels "servico.solucao.cluster.k8s.bb/dimensao"{{`}}`}}'
                    clusterIndex: '{{`{{`}}index .metadata.labels "servico.solucao.cluster.k8s.bb/index"{{`}}`}}'
                    clusterSite: '{{`{{`}}index .metadata.labels "cluster.k8s.bb/site"{{`}}`}}'
                    clusterTemplateID: '{{`{{`}}index .metadata.labels "openshift.cluster.k8s.bb/templateID"{{`}}`}}'
