approval_policy = { granular = {
  sandbox_approval = true,
  rules = false,
  mcp_elicitations = true,
  request_permissions = false,
  skill_approval = false
} }

sandbox_mode = "workspace-write"
allow_login_shell = false

[sandbox_workspace_write]
network_access = true

[windows]
sandbox = "elevated"

[features]
child_agents_md = true
