global:
  clusterSolucao: ''
  clusterServico: ''
  clusterDimensao: ''
  clusterName: ''
  clusterIndex: ''
  clusterTemplateID:
  clusterSite: ''
  servicoSigla: ''
  servicoEnv: ''
  servicoNome: ''

sre-aut-controller:
  enabled: true
  items:
    - enabled: true
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: sre-aut-controller-sa
        namespace: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"

    - enabled: true
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: sre-aut-controller
      rules:
        - apiGroups: [""]
          resources: ["services", "persistentvolumeclaims", "configmaps","events"]
          verbs: ["get", "list", "watch"]
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["apps"]
          resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["batch"]
          resources: ["jobs", "cronjobs"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["networking.k8s.io"]
          resources: ["ingresses", "networkpolicies"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["certificado.psc.bb.com.br/v1"]
          resources: ["bbcerts"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["psc.bb.com.br/v1"]
          resources: ["dnsingresses"]
          verbs: ["get", "list", "watch"]

    - enabled: true
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: sre-aut-controller-binding
      subjects:
        - kind: ServiceAccount
          name: sre-aut-controller-sa
          namespace: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
      roleRef:
        kind: ClusterRole
        name: sre-aut-controller
        apiGroup: rbac.authorization.k8s.io

    - enabled: true
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
        namespace: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
        labels:
          app: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/sigla: "{{ .Values.global.servicoSigla }}"
          release.k8s.bb.ambiente: "{{ .Values.global.servicoEnv }}"
          chart.release.k8s.bb/name: psc-sre-aut-controller
          release.k8s.bb/deploy: regular
          
      spec:
        revisionHistoryLimit: 7
        replicas: 1
        strategy:
          type: RollingUpdate
        selector:
          matchLabels:
            app: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
            release: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
            release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
            release.k8s.bb/sigla: "{{ .Values.global.servicoSigla }}"
            release.k8s.bb/deploy: regular
        template:
          metadata:
            labels:
              app: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
              release: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
              release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
              release.k8s.bb/sigla: "{{ .Values.global.servicoSigla }}"
              release.k8s.bb.ambiente: "{{ .Values.global.servicoEnv }}"
              release.k8s.bb/deploy: regular
              
          spec:
            serviceAccountName: sre-aut-controller-sa
            imagePullSecrets:
              - name: atfregistry
            # initContainers:     
            # affinity:
            #   podAntiAffinity:
            #     preferredDuringSchedulingIgnoredDuringExecution:
            #     - podAffinityTerm:
            #         labelSelector:
            #           matchExpressions:
            #           - key: release
            #             operator: In
            #             values:
            #             - "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
            #         topologyKey: kubernetes.io/hostname
            #       weight: 100
            nodeSelector:
              papel.node.k8s.bb/worker: "true"
              node.k8s.bb/servico: psc-nodes-apps-gir
            tolerations:
            - key: "node.k8s.bb/servico"
              operator: Equal
              value: "psc-nodes-apps-gir" 
              effect: "NoSchedule"
            containers:
            - name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
              image: docker.binarios.intranet.bb.com.br/bb/psc/psc-sre-automacao-controller:2.3.4
              imagePullPolicy: "IfNotPresent"
              livenessProbe:
                failureThreshold: 6
                httpGet:
                  path: /health
                  port: 3000
                initialDelaySeconds: 120
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
              readinessProbe:
                failureThreshold: 6
                httpGet:
                  path: /ready
                  port: 3000
                initialDelaySeconds: 120
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
              resources:
                requests:
                  cpu: 100m
                  memory: 250Mi
                limits:
                  cpu: 150m
                  memory: 375Mi
              env:
                - name: MP_OPENAPI_SERVERS
                  value: "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br" 
                - name: ENABLE_INDEX
                  value: index.html
                - name: ENABLE_SWAGGER
                  value: "false"
                - name: OSS_BUCKET
                  valueFrom:
                    secretKeyRef:
                      name: oss-credentials
                      key: oss_bucket
                - name: OSS_ACCESS_KEY_FILE
                  value: /var/run/secrets/oss/oss_access_key
                - name: OSS_SECRET_KEY_FILE
                  value: /var/run/secrets/oss/oss_secret_key
                - name: OSS_ENDPOINT
                  valueFrom:
                    secretKeyRef:
                      name: oss-credentials
                      key: oss_endpoint
                - name: AWS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: oss-credentials
                      key: aws_region
                - name: AUTH_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: auth-api-key
                      key: jwt_secret
                - name: JWT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: auth-api-key
                      key: jwt_secret
                - name: AUTH_API_KEYS_SCOPES
                  valueFrom:
                    secretKeyRef:
                      name: auth-api-key
                      key: auth_api_keys_scopes
                - name: SCOPE_EXECUTE_AUTOMATION
                  valueFrom:
                    secretKeyRef:
                      name: auth-api-key
                      key: scope_execute_automation
                - name: SCOPE_SEND_LOGS
                  valueFrom:
                    secretKeyRef:
                      name: auth-api-key
                      key: scope_send_logs
                - name: SCOPE_READ_STATUS
                  valueFrom:
                    secretKeyRef:
                      name: auth-api-key
                      key: scope_read_status
                - name: SCOPE_REGISTER_AGENT
                  valueFrom:
                    secretKeyRef:
                      name: auth-api-key
                      key: scope_register_agent
                - name: JWT_ISSUER
                  value: psc-sre-automacao-controller
                - name: JWT_AUDIENCE
                  value: psc-sre-automacao-agent
                - name: OSS_FORCE_PATH_STYLE
                  value: "1"
                - name: TRACE_DEBUG
                  value: "1"

    - enabled: true
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
        namespace: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
        labels:
          app: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/project: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/sigla: "{{ .Values.global.servicoSigla }}"
          release.k8s.bb.appName: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb.ambiente: "{{ .Values.global.servicoEnv }}"
          chart.release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          projeto: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          sigla: "{{ .Values.global.servicoSigla }}"
      spec:
        type: ClusterIP
        selector:
          app: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
        ports:
          - name: http
            port: 80
            targetPort: 3000

    - enabled: true
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"
        namespace: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
        labels:
          app: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/project: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/sigla: "{{ .Values.global.servicoSigla }}"
          release.k8s.bb.appName: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb.ambiente:   "{{ .Values.global.servicoEnv }}"
          chart.release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/ingress: interno
          ingress.k8s.bb/class: nginx
          chart.k8s.bb/modificado: "versao-ingress"
        annotations:
          haproxy.org/timeout-client: 1800s
          haproxy.org/timeout-connect: 30s
          haproxy.org/timeout-server: 1800s
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
      spec:
        rules:
        - host: "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"
          http:
            paths:
            - path: "/"
              pathType: Prefix
              backend:
                service:
                  name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
                  port:
                    number: 80
        tls:
        - hosts:
          - "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"
          secretName: "{{ .Values.global.servicoNome }}"
                  
    - enabled: true
      apiVersion: psc.bb.com.br/v1
      kind: DnsIngress
      metadata:
        name: "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"
        namespace: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
        labels:
          app: dnsingress
          release: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/name: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/project: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
          release.k8s.bb/sigla: "{{ .Values.global.servicoSigla }}"
          chart.release.k8s.bb/name: dnsingress
          chart.release.k8s.bb/version: 2.0.0
      spec:
        ingressClass: nginx
        hostname: "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"

    - enabled: true
      apiVersion: certificado.psc.bb.com.br/v1
      kind: BBCert
      metadata:
        name: "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"
        namespace: "{{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}"
      spec:
        autoRenew:
          enabled: true
          qtDaysBeforeCertExpirion: 30
        custodianteCertificado:
          matriculaBB: F6321212
        dadosCertificado:
          alternativesNames:
          - "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"
          ambientePKI: "{{ .Values.global.servicoEnv }}"
          commomName: "{{ .Values.global.servicoNome }}.psc.{{ .Values.global.clusterName }}.bb.com.br"
          secretNameToExport: "{{ .Values.global.servicoNome }}"
          sigla: "{{ .Values.global.servicoSigla }}"
          ttl: 365

    # - enabled: false
    #   apiVersion: autoscaling/v2
    #   kind: HorizontalPodAutoscaler
    #   metadata:
    #     name: {{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}
    #     namespace: {{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}
    #     labels:
    #       app: {{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}
    #       release: {{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}
    #       release.k8s.bb/name: {{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}
    #       release.k8s.bb/sigla: {{ .Values.global.servicoSigla }}
    #       release.k8s.bb/deploy: regular
    #   spec:
    #     scaleTargetRef:
    #       apiVersion: apps/v1
    #       kind: Deployment
    #       name: {{ .Values.global.servicoSigla }}-{{ .Values.global.servicoNome }}

    #     minReplicas: {{ default 1 .Values.hpa.minReplicas }}
    #     maxReplicas: {{ default 5 .Values.hpa.maxReplicas }}

    #     metrics:
    #       - type: Resource
    #         resource:
    #           name: cpu
    #           target:
    #             type: Utilization
    #             averageUtilization: {{ default 70 .Values.hpa.cpu.averageUtilization }}
    #       - type: Resource
    #         resource:
    #           name: memory
    #           target:
    #             type: Utilization
    #             averageUtilization: {{ default 70 .Values.hpa.memory.averageUtilization }}
