name: "⚙ Esteira Padrão"
on:
  push:
    branches:
      - main
      - "fix/**"
      - "feat/**"
      - "feature/**"
    tags:
      - '*'
  workflow_dispatch:
permissions:
  actions: write
  contents: write
jobs:
  CI:
    uses: bbvinet/aic-chaplin-admin-workflows/.github/workflows/workflow-padrao.yml@main
    secrets: inherit
